{% set name = "gwcelery" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03eeba9f0e0d85d6492b4d180685427856be887b723d7271f907dacd43cfa954

build:
  entry_points:
    - gwcelery = gwcelery:app.start
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=30.3.0
  run:
    - bilby_pipe >=0.3.8
    - celery >=4.4.0
    - comet
    - corner
    - dnspython
    - flask
    - flask-caching
    - gracedb-sdk >=0.1.4
    - gwdatafind
    - gwpy
    - healpy
    - imapclient
    - jinja2
    - lalsuite
    - ligo-followup-advocate >=1.1.6
    - ligo-gracedb >=2.3.0
    - ligo-raven >=1.17
    - ligo-segments
    - ligo.skymap >=0.1.13
    - lscsoft-glue
    - lxml
    - numpy
    - p_astro 0.8.1
    - pygcn >=0.1.19
    - python >=3.6
    - python-ligo-lw
    - redis-py
    - safe-netrc
    - sentry-sdk
    - service_identity
    - sleek-lvalert >=0.0.4
    - tornado >=5
    - voeventlib >=1.2
    - werkzeug >=0.15.0,<1.0.0a0

test:
  imports:
    - gwcelery
  requires:
    # for scikit-learn
    - openblas
    # for mpi
    - openssh
    # for gwcelery's test suite
    - pytest >=3.0
    - pytest-flask
    - pytest-socket
  commands:
    - gwcelery --version
    - python -m pytest --pyargs gwcelery

about:
  home: https://git.ligo.org/emfollow/gwcelery
  dev_url: https://git.ligo.org/emfollow/gwcelery
  doc_url: https://gwcelery.readthedocs.io/en/latest/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.rst
  summary: Hipster pipeline for annotating LIGO events
  description: |
    GWCelery is a simple and reliable package for annotating and orchestrating
    LIGO/Virgo alerts, built from widely used open source components.

extra:
  recipe-maintainers:
    - duncanmmacleod
