{% set name = "gwcelery" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 567f07025ab1dedde55d8be5b310de1ed82bc8144337cc673dd243a63908b8f4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - gwcelery = gwcelery:app.start

requirements:
  host:
    - python >=3.6,<3.7
    - pip
    - setuptools >=30.3.0
  run:
    - astropy
    - celery >=4.2.0
    - celery-eternal >=0.0.3
    - comet
    - corner
    - flask
    - flask-caching
    - flower
    - gwdatafind
    - gwpy
    - healpy
    - jinja2
    - lalsuite >=6.52
    - ligo-followup-advocate >=0.0.21
    - ligo-gracedb >=2.2.0
    - ligo-raven >=1.10
    - ligo-segments
    - ligo.skymap >=0.1.1
    - lscsoft-glue
    - lxml
    - numpy
    - p_astro 0.4
    - pygcn >=0.1.19
    - python >=3.6,<3.7
    - redis-py <3.2.0
    - safe-netrc
    - sentry-sdk
    - service_identity
    - sleek-lvalert >=0.0.4
    - tornado <6.0a0
    - voeventlib >=1.2

test:
  imports:
    - gwcelery
  requires:
    - pytest >=3.0
    - pytest-socket
  commands:
    - gwcelery --version
    - python -m pytest --pyargs $PKG_NAME

about:
  home: https://git.ligo.org/emfollow/gwcelery
  license: GPLv2+
  license_family: GPL
  license_file: doc/license.rst
  summary: Hipster pipeline for annotating LIGO events
  doc_url: https://gwcelery.readthedocs.io/en/latest/
  dev_url: https://git.ligo.org/emfollow/gwcelery
  description: |
    GWCelery is a simple and reliable package for annotating and
    orchestrating LIGO/Virgo alerts, built from widely used
    open source components.

extra:
  recipe-maintainers:
    - duncanmmacleod
