{% set name = "gwcelery" %}
{% set version = "0.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e4adfee9bd41dd5c462443d49842ce27158ef6440bf44945fe8c13239fa04413

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - gwcelery = gwcelery:app.start

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=30.3.0
  run:
    - astropy <4
    - celery 4.3.0
    - comet
    - dnspython
    - flask
    - flask-caching
    - flower
    - gwdatafind
    - gwpy <=0.15.0
    - healpy
    - imapclient
    - jinja2
    - kombu <=4.5.0
    - lalsuite 6.60
    - ligo-followup-advocate 1.1.3
    - ligo-gracedb >=2.3.0
    - ligo-raven >=1.17
    - ligo-segments
    - ligo.skymap 0.1.13
    - lscsoft-glue
    - lxml
    - numpy
    - p_astro 0.8.1
    - pygcn >=0.1.19
    - python >=3.6
    - python-ligo-lw
    - redis-py
    - safe-netrc
    - scipy <1.3.0
    - sentry-sdk
    - service_identity
    - sleek-lvalert >=0.0.4
    - tornado <6
    - voeventlib >=1.2
    - werkzeug >=0.15.0

test:
  imports:
    - gwcelery
  requires:
    - pytest >=3.0
    - pytest-socket
    - pytest-flask
  commands:
    - gwcelery --version
    - python -m pytest --pyargs gwcelery

about:
  home: "https://git.ligo.org/emfollow/gwcelery"
  dev_url: "https://git.ligo.org/emfollow/gwcelery"
  doc_url: "https://gwcelery.readthedocs.io/en/latest/"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE.rst"
  summary: "Hipster pipeline for annotating LIGO events"
  description: |
    GWCelery is a simple and reliable package for annotating and orchestrating
    LIGO/Virgo alerts, built from widely used open source components.

extra:
  recipe-maintainers:
    - duncanmmacleod
