travis:
  secure:
    BINSTAR_TOKEN: k5yRWK0U7CQLODyYqFMgnjatqmkfJnVaYtc/AHHlp4c3fwhDfmmLYRdwjPT27XgfSn1Od04L3zDquL13TjPSbE1vYW1yVBnamNclJD5KU1bcBpHJIp47dVLPUoZcOU8LjZFf/TzSptsKwv7FdEoU4PCD5cwN/Njkp/DHfnD+4ubTt2nr0aheUISiVpSDf/FayrH8Hx/xEyK66d6CPujRM4guetUlMOfvu0Ju9PW9Onm5Ge2JuFg2ajPrI3pIQa4+xgthrrh4fG+Z8S59EuqI+4a9R8uxdD0J3P4ErhTG0coLqPyilognw0LZ9zglz/Wk84ZaXlyyX5FftcCqaqzw9ZogozDfqVVhw/cr66G59tRF7UJ6k1JCXUXNmhaR8WanAW49P6gaO1PPBGa+CudoaZBtV7ymJk7OZFbamh2D2QOenlCAp4+gTByaq8q2/i8iWJRq1umBnybBoqqJdKmEwtM58af5YBE/UnyqgWAxemZ2H3cAh9+aAMb4ydnWbNHjB7CjWV7Oj4pIaYkdwP2+REY3QcccgsltqmQEqfLxgV4ya8XbwM8PfPFakHY/iqVSE39TLimvSsSltL1+ApGqLeB8bMVU/xN0gzzK4O6x0LGFG0LZ75cKCrKxXtqQJf2GDdtKYtp+jswEnVyoVQpoiWZbshbNlEVixJccz0pPIyc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
